# Generated by Django 5.1.4 on 2025-02-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_active",
            new_name="is_verified",
        ),
    ]
