# Generated by Django 5.1.4 on 2024-12-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
