# Generated by Django 5.1.4 on 2025-01-02 18:27

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0005_alter_customuser_email_alter_customuser_password"),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name="customuser",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["first_name"], name="users_custo_first_n_e32121_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["last_name"], name="users_custo_last_na_dbfaf3_gin"
            ),
        ),
    ]
