# Generated by Django 5.1.4 on 2025-01-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_users_custo_first_n_e32121_gin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_active",
            new_name="is_online",
        ),
    ]
