# Generated by Django 5.1.4 on 2025-01-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_is_active_customuser_is_online"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "for_user"), name="unique_user_for_user"
            ),
        ),
    ]
