# Generated by Django 5.1.4 on 2025-01-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0010_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                fields=("email", "is_trainer"), name="unique_email_is_trainer"
            ),
        ),
    ]
