# Generated by Django 5.1.4 on 2025-01-16 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_customuser_unique_email_is_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="unique_identifier",
            field=models.CharField(default=123, max_length=512, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, validators=[django.core.validators.EmailValidator()]
            ),
        ),
    ]
