# Generated by Django 5.1.4 on 2025-02-07 02:29

import TrackHub.trackhub_bucket
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=TrackHub.trackhub_bucket.TrackHubMediaStorage(),
                upload_to="",
                validators=[users.validators.validate_image_size],
            ),
        ),
    ]
