# Generated by Django 5.1.4 on 2025-02-10 07:50

import TrackHub.trackhub_bucket
import django.contrib.postgres.indexes
import django.db.models.functions.text
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0014_alter_customuser_avatar"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customuser",
            name="users_custo_first_n_e32121_gin",
        ),
        migrations.RemoveIndex(
            model_name="customuser",
            name="users_custo_last_na_dbfaf3_gin",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=TrackHub.trackhub_bucket.TrackHubMediaStorage(),
                upload_to="avatars/",
                validators=[users.validators.validate_image_size],
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower("first_name"),
                    name="gin_trgm_ops",
                ),
                name="first_name_gin_trgm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower("last_name"),
                    name="gin_trgm_ops",
                ),
                name="last_name_gin_trgm_idx",
            ),
        ),
    ]
