# Generated by Django 5.1.4 on 2025-02-11 07:09

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_customuser_users_custo_first_n_e32121_gin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, validators=[users.validators.name_validator]
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, validators=[users.validators.name_validator]
            ),
        ),
    ]
