# Generated by Django 5.1.4 on 2024-12-18 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trainers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="breaks",
            field=models.ManyToManyField(to="trainers.break"),
        ),
        migrations.AddField(
            model_name="trainer",
            name="holidays",
            field=models.ManyToManyField(to="trainers.holiday"),
        ),
        migrations.AddField(
            model_name="trainer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="trainers.trainer",
            ),
        ),
        migrations.AddField(
            model_name="trainerweekend",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="trainers.trainer"
            ),
        ),
        migrations.AddField(
            model_name="userexercises",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="trainers.exercise"
            ),
        ),
        migrations.AddField(
            model_name="userexercises",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_exercises",
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="trainerweekend",
            name="weekday",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="trainers.weekday"
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="weekends",
            field=models.ManyToManyField(
                through="trainers.TrainerWeekend", to="trainers.weekday"
            ),
        ),
        migrations.AddField(
            model_name="wholeexperience",
            name="trainer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whole_experience",
                to="trainers.trainer",
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="work_hours",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="trainers.workhours"
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="trainers.exercise"
            ),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="trainers.workout"
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="exercises",
            field=models.ManyToManyField(
                through="trainers.WorkoutExercise", to="trainers.exercise"
            ),
        ),
    ]
