# Generated by Django 5.1.4 on 2024-12-19 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="breaks",
            field=models.ManyToManyField(blank=True, null=True, to="trainers.break"),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="holidays",
            field=models.ManyToManyField(blank=True, null=True, to="trainers.holiday"),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="weekends",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="trainers.TrainerWeekend",
                to="trainers.weekday",
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="work_hours",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trainers.workhours",
            ),
        ),
    ]
