# Generated by Django 5.1.4 on 2024-12-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0003_alter_trainer_breaks_alter_trainer_holidays_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="breaks",
            field=models.ManyToManyField(blank=True, to="trainers.break"),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="holidays",
            field=models.ManyToManyField(blank=True, to="trainers.holiday"),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="weekends",
            field=models.ManyToManyField(
                blank=True, through="trainers.TrainerWeekend", to="trainers.weekday"
            ),
        ),
    ]
