# Generated by Django 5.1.4 on 2024-12-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
         "trainers",
         "0004_alter_trainer_breaks_alter_trainer_holidays_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="description",
            field=models.CharField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
    ]
