# Generated by Django 5.1.4 on 2024-12-28 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0005_alter_trainer_address_alter_trainer_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="user",
            new_name="created_by",
        ),
        migrations.AddField(
            model_name="workout",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workout",
            name="name",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workout",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_workouts",
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
