# Generated by Django 5.1.4 on 2024-12-28 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0006_rename_user_workout_created_by_workout_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-12-28 00:00:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exercise",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_exercises",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
