# Generated by Django 5.1.4 on 2024-12-28 19:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0007_rename_available_for_exercise_shared_with_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserExercises",
        ),
    ]
