# Generated by Django 5.1.4 on 2024-12-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0008_alter_exercise_shared_with_delete_userexercises"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-12-28 00:00:00"
            ),
            preserve_default=False,
        ),
    ]
