# Generated by Django 5.1.4 on 2024-12-28 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0009_workoutexercise_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="break",
            old_name="end",
            new_name="end_time",
        ),
        migrations.RenameField(
            model_name="break",
            old_name="start",
            new_name="start_time",
        ),
        migrations.RenameField(
            model_name="holiday",
            old_name="end",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="holiday",
            old_name="start",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="workhours",
            old_name="end",
            new_name="end_time",
        ),
        migrations.RenameField(
            model_name="workhours",
            old_name="start",
            new_name="start_time",
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_workoutexercises",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
