# Generated by Django 5.1.4 on 2024-12-28 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0010_rename_end_break_end_time_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrainerWeekend",
            new_name="TrainerWeek",
        ),
    ]
