# Generated by Django 5.1.4 on 2024-12-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0011_rename_trainerweekend_trainerweek"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrainerWeek",
            new_name="TrainerWeekend",
        ),
        migrations.AlterField(
            model_name="weekday",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
