# Generated by Django 5.1.4 on 2024-12-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trainers",
            "0013_workoutexercise_created_by_alter_workout_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
