# Generated by Django 5.1.4 on 2024-12-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0014_trainer_is_active_trainer_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="is_male",
            field=models.BooleanField(default=True),
        ),
    ]
