# Generated by Django 5.1.4 on 2024-12-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0015_trainer_is_male"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="MuscleGroupCategory",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="category",
            new_name="muscle_group_category",
        ),
        migrations.AddField(
            model_name="trainer",
            name="price_per_hour",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
