# Generated by Django 5.1.4 on 2024-12-30 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0016_rename_category_musclegroupcategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryOfTrainers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainers.categoryoftrainers",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainers.trainer",
                    ),
                ),
            ],
            options={
                "unique_together": {("trainer", "category")},
            },
        ),
        migrations.AddField(
            model_name="trainer",
            name="trainer_categories",
            field=models.ManyToManyField(
                through="trainers.TrainerCategory", to="trainers.categoryoftrainers"
            ),
        ),
    ]
