# Generated by Django 5.1.4 on 2025-01-02 17:32

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0017_categoryoftrainers_trainercategory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name="trainer",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description"], name="trainers_tr_descrip_39229f_gin"
            ),
        ),
    ]
