# Generated by Django 5.1.4 on 2025-01-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0019_create_extension_pg_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="minimum_workout_duration",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="trainer",
            name="workout_duration_devided_by_value",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
