# Generated by Django 5.1.4 on 2025-01-03 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0020_trainer_minimum_workout_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainer",
            name="work_hours",
        ),
        migrations.AddField(
            model_name="workhours",
            name="trainer",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="trainers.trainer",
            ),
            preserve_default=False,
        ),
    ]
