# Generated by Django 4.2.9 on 2025-01-04 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trainers", "0021_remove_trainer_work_hours_workhours_trainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
