# Generated by Django 5.1.4 on 2025-01-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0022_alter_trainer_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MuscleGroupCategory",
            new_name="ExerciseCategory",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="muscle_group_category",
            new_name="ExerciseCategory",
        ),
    ]
