# Generated by Django 5.1.4 on 2025-01-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0023_rename_musclegroupcategory_exercisecategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="ExerciseCategory",
        ),
    ]
