# Generated by Django 5.1.4 on 2025-01-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0024_remove_exercise_exercisecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="trainers.exercisecategory",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="trainerweekend",
            constraint=models.UniqueConstraint(
                fields=("trainer", "weekday"), name="unique_trainer_weekday"
            ),
        ),
    ]
