# Generated by Django 5.1.4 on 2025-01-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0025_exercise_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="trainer_categories",
            field=models.ManyToManyField(
                blank=True,
                through="trainers.TrainerCategory",
                to="trainers.categoryoftrainers",
            ),
        ),
    ]
