# Generated by Django 5.1.4 on 2025-01-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0026_alter_trainer_trainer_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
