# Generated by Django 5.1.4 on 2025-01-07 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0028_alter_workhours_trainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workhours",
            name="trainer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workhours",
                to="trainers.trainer",
            ),
        ),
    ]
