# Generated by Django 5.1.4 on 2025-01-09 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0029_alter_workhours_trainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainerweekend",
            name="weekday",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trainers.weekday",
            ),
        ),
    ]
