# Generated by Django 5.1.4 on 2025-01-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0030_alter_trainerweekend_weekday"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainerweekend",
            old_name="weekday",
            new_name="weekdays",
        ),
    ]
