# Generated by Django 5.1.4 on 2025-01-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0031_rename_weekday_trainerweekend_weekdays"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="trainerweekend",
            name="unique_trainer_weekday",
        ),
        migrations.AddConstraint(
            model_name="trainerweekend",
            constraint=models.UniqueConstraint(
                fields=("trainer", "weekdays"), name="unique_trainer_weekdays"
            ),
        ),
    ]
