# Generated by Django 5.1.4 on 2025-01-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0032_remove_trainerweekend_unique_trainer_weekday_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="trainerweekend",
            name="unique_trainer_weekdays",
        ),
        migrations.RenameField(
            model_name="trainerweekend",
            old_name="weekdays",
            new_name="weekday",
        ),
        migrations.AddConstraint(
            model_name="trainerweekend",
            constraint=models.UniqueConstraint(
                fields=("trainer", "weekday"), name="unique_trainer_weekday"
            ),
        ),
    ]
