# Generated by Django 5.1.4 on 2025-01-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0033_remove_trainerweekend_unique_trainer_weekdays_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrainerWeekend",
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='weekends',
        ),
        migrations.AddField(
            model_name="trainer",
            name="weekends",
            field=models.ManyToManyField(blank=True, to="trainers.weekday"),
        ),
    ]
