# Generated by Django 5.1.4 on 2025-01-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0034_alter_trainer_weekends_delete_trainerweekend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
