# Generated by Django 5.1.4 on 2025-01-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0035_alter_exercise_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='trainer_categories',
        ),
        migrations.AddField(
            model_name="trainer",
            name="trainer_categories",
            field=models.ManyToManyField(blank=True, to="trainers.categoryoftrainers"),
        ),
        migrations.DeleteModel(
            name="TrainerCategory",
        ),
    ]
