# Generated by Django 5.1.4 on 2025-01-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0036_alter_trainer_trainer_categories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutexercise",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="shared_with",
        ),
    ]
