# Generated by Django 5.1.4 on 2025-01-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0037_remove_workoutexercise_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutexercise",
            name="created_at",
        ),
    ]
