# Generated by Django 5.1.4 on 2025-01-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0038_remove_workoutexercise_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
