# Generated by Django 5.1.4 on 2025-01-12 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0039_workout_is_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="available_for",
            field=models.ManyToManyField(
                blank=True,
                related_name="available_workout_exercises",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
