# Generated by Django 5.1.4 on 2025-01-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0040_workoutexercise_available_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="rest_between_workout_exercises",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
