# Generated by Django 5.1.4 on 2025-01-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0041_workout_rest_between_workout_exercises"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainer",
            old_name="price_per_hour",
            new_name="price_per_minimum_workout_duration",
        ),
    ]
