# Generated by Django 5.1.4 on 2025-01-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "trainers",
            "0042_rename_price_per_hour_trainer_price_per_minimum_workout_duration",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="category",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="shared_with",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="exercises",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="shared_with",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="workout",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="available_for",
        ),
        migrations.DeleteModel(
            name="ExerciseCategory",
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
        migrations.DeleteModel(
            name="Workout",
        ),
        migrations.DeleteModel(
            name="WorkoutExercise",
        ),
    ]
