# Generated by Django 5.1.4 on 2025-01-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "trainers",
            "0043_remove_exercise_category_remove_exercise_created_by_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="user",
        ),
    ]
