# Generated by Django 5.1.4 on 2025-02-11 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0045_remove_trainer_trainers_tr_descrip_39229f_gin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainer",
            name="address",
        ),
        migrations.AddField(
            model_name="trainer",
            name="is_able_to_visit",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainers.trainer",
                    ),
                ),
            ],
        ),
    ]
