# Generated by Django 5.1.4 on 2024-12-19 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_initial"),
        ("trainers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainersofuser",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients_of_trainer",
                to="trainers.trainer",
            ),
        ),
        migrations.AlterField(
            model_name="trainersofuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainers_of_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
