# Generated by Django 5.1.4 on 2025-01-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_workoutsession"),
        ("trainers", "0022_alter_trainer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="trainer_of_user",
        ),
        migrations.CreateModel(
            name="TrainersOfCLient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favourite", models.BooleanField(default=False)),
                ("found_by_link", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainers_of_client",
                        to="clients.client",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients_of_trainer",
                        to="trainers.trainer",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TrainersOfUser",
        ),
    ]
