# Generated by Django 5.1.4 on 2025-03-08 08:26

import TrackHub.trackhub_bucket
import django.core.validators
import django.db.models.deletion
import users.validators
import workout_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        storage=TrackHub.trackhub_bucket.TrackHubMediaStorage(),
                        upload_to="gym_equipment/",
                        validators=[users.validators.validate_image],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFitnessProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workout_limitation", models.PositiveIntegerField(default=25)),
                ("exercise_limitation", models.PositiveIntegerField(default=50)),
                ("plans_limitation", models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name="exercise",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=TrackHub.trackhub_bucket.TrackHubMediaStorage(),
                upload_to="exercises/previews/",
                validators=[users.validators.validate_image],
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="reps_measured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="value",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(3600),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="exercises/videos/",
                validators=[workout_manager.validators.validate_video_size],
            ),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="reps",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="rest_time",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(3600),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="sets",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="gym_equipment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="workout_manager.gymequipment",
            ),
        ),
    ]
