# Generated by Django 5.1.4 on 2025-03-08 12:22

import django.core.validators
import django.db.models.deletion
import workout_manager.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workout_manager",
            "0002_gymequipment_userfitnessprogram_exercise_preview_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="value",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="reps",
        ),
        migrations.AddField(
            model_name="exercise",
            name="instructions",
            field=models.JSONField(
                default="[]",
                validators=[workout_manager.validators.validate_instructions],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userfitnessprogram",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fitness_program",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="value",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(3600),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="gym_equipment",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="gymequipment",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="rest_time",
            field=models.PositiveIntegerField(
                default=60,
                validators=[
                    django.core.validators.MaxValueValidator(3600),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="gym_equipment",
            field=models.ManyToManyField(
                related_name="exercises", to="workout_manager.gymequipment"
            ),
        ),
    ]
