# Generated by Django 5.1.4 on 2025-03-09 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workout_manager",
            "0003_remove_exercise_value_remove_workoutexercise_reps_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterModelOptions(
            name="workoutexercise",
            options={"ordering": ["order"]},
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="created_at",
            new_name="changed_at",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="reps_measured",
            new_name="is_measured_in_reps",
        ),
        migrations.RenameField(
            model_name="workout",
            old_name="created_at",
            new_name="changed_at",
        ),
        migrations.RenameField(
            model_name="workoutexercise",
            old_name="rest_time",
            new_name="rest_time_after_set",
        ),
        migrations.AddField(
            model_name="exercise",
            name="original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workout_manager.exercise",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exercise",
            unique_together={
                ("name", "description", "preview", "video", "created_by", "original")
            },
        ),
        migrations.RemoveField(
            model_name="workout",
            name="rest_between_workout_exercises",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="shared_with",
        ),
        migrations.AlterUniqueTogether(
            name="workoutexercise",
            unique_together={("workout", "order")},
        ),
        migrations.AddField(
            model_name="exercise",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exercise",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workout",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workout",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workout",
            name="original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workout_manager.workout",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="created_by",
            field=models.ForeignKey(
                default=60,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_exercises",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workout",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_workouts",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_exercises",
                to="workout_manager.exercise",
            ),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="workout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_exercises",
                to="workout_manager.workout",
            ),
        ),
        migrations.CreateModel(
            name="UserWorkoutManagerLimitaion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workout_limitation", models.PositiveIntegerField(default=50)),
                ("exercise_limitation", models.PositiveIntegerField(default=100)),
                ("plans_limitation", models.PositiveIntegerField(default=25)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_manager_limitation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyFitnessPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_weekly_fitness_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workout_manager.weeklyfitnessplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyFitnessPlanWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_day",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                (
                    "weekly_fitness_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_fitness_plan_workouts",
                        to="workout_manager.weeklyfitnessplan",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_fitness_plan_workouts",
                        to="workout_manager.workout",
                    ),
                ),
            ],
            options={
                "ordering": ["week_day"],
            },
        ),
        migrations.AddField(
            model_name="weeklyfitnessplan",
            name="workouts",
            field=models.ManyToManyField(
                through="workout_manager.WeeklyFitnessPlanWorkout",
                to="workout_manager.workout",
            ),
        ),
        migrations.DeleteModel(
            name="UserFitnessProgram",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="shared_with",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="category",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="available_for",
        ),
        migrations.AddField(
            model_name="exercise",
            name="category",
            field=models.ManyToManyField(
                related_name="exercises", to="workout_manager.exercisecategory"
            ),
        ),
    ]
