# Generated by Django 5.1.4 on 2025-03-10 07:18

import workout_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workout_manager",
            "0005_rename_userworkoutmanagerlimitaion_userworkoutmanagerlimitation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="instructions",
            field=models.JSONField(
                default=list,
                validators=[workout_manager.validators.validate_instructions],
            ),
        ),
    ]
